### ISSUE TITLE
Feature Request: use puppeteer-core when Chrome is available in system

### ISSUE THREAD

**Issue by guoyunhe** [sindresorhus/capture-website#104]
puppeteer is huge and download Chromium can be slow.

What about:

1. If the computer, most likely, already has Chrome/Edge installed, install puppeteer-core.
2. If the computer, doesn't have Chrome like browsers (e.g. CI containers), install puppeteer.

**Comment by guoyunhe** [comment]
Here is my try https://github.com/sindresorhus/capture-website/compare/main...guoyunhe:capture-website-core:main

I replaced puppeteer with puppeteer-core. Before launching puppeteer-core, I detect existence of system Chrome browser. If available, use it. If not, run install.js script to download Chromium.

**Comment by sindresorhus** [comment]
Glad you managed to solve the problem for yourself, but it's not something I plan to do here.
