### ISSUE TITLE
Error: createRequire only supports 'file://' URLs for the 'filename' parameter.

### ISSUE THREAD

**Issue by darwinprayoga** [sindresorhus/capture-website#106]
Watcher File change detected! Restarting!
error: Uncaught (in promise) Error: createRequire only supports 'file://' URLs for the 'filename' parameter. Received 'https://esm.sh/v90/puppeteer@16.1.0/deno/lib/esm/puppeteer/compat.js'
          throw new Error(
                ^
    at createRequire (https://deno.land/std@0.151.0/node/module.ts:690:17)
    at https://esm.sh/v90/puppeteer@16.1.0/deno/lib/esm/puppeteer/compat.js:2:227
Watcher Process finished. Restarting on file change...

**Comment by sindresorhus** [comment]
The error is coming from `puppeteer` so you should ask at that project instead.
