### ISSUE TITLE
Could be useful to support  a commonjs version

### ISSUE THREAD

**Issue by rubixibuc** [sindresorhus/capture-website#112]
Hi!

I'm unable to run the es6 import version easily and it would be helpful to supply a common js artifact for people not running a version of node support es6 imports.

**Comment by sindresorhus** [comment]
I have no plans to do that.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
> people not running a version of node support es6 imports.

All maintained Node.js version support ESM.
