### ISSUE TITLE
npm warn deprecated @cliqz/adblocker-puppeteer@1.34.0

### ISSUE THREAD

**Issue by rvalitov** [sindresorhus/capture-website#129]
npm warn deprecated @cliqz/adblocker-puppeteer@1.34.0: This project has been renamed to @ghostery/adblocker-puppeteer. Install using @ghostery/adblocker-puppeteer instead

**Comment by sindresorhus** [comment]
Fixed in https://github.com/sindresorhus/capture-website/releases/tag/v4.2.0
