### ISSUE TITLE
Add `clip` option 

### ISSUE THREAD

**Issue by nikkki** [sindresorhus/capture-website#20]
Implementation of puppeteer [`clip`](https://github.com/GoogleChrome/puppeteer/blob/v1.13.0/docs/api.md#pagescreenshotoptions) functionality.  
Example:
```
{
    clip: {
        x: 10,
        y: 30,
        height: 300,
        width: 200
    }
}
```

- `x` - `<number>` - x-coordinate of top-left corner of clip area;
- `y` - `<number>` - y-coordinate of top-left corner of clip area;
- `width` - `<number>` - width of clipping area;
- `height` - `<number>` - height of clipping area.

**Comment by sindresorhus** [comment]
What's your use-case? We already have the [`element` option](https://github.com/sindresorhus/capture-website#element) which uses `clip` internally.

**Comment by nikkki** [comment]
Yeah, I know about `element` option, but in my case is more handy to use exactly `clip` from puppeteer. I'm going to implement this feature and make a PR tomorrow. Ok?

**Comment by sindresorhus** [comment]
Why/how is it more handy? Can you please elaborate?

**Comment by nikkki** [comment]
This is a one of business requirements for the service, which I'm developing:)

**Comment by sindresorhus** [comment]
Alright. PR welcome. Should come with docs and tests too.

**Comment by nikkki** [comment]
Awesome!

**Comment by sindresorhus** [comment]
Don't forget to also update https://github.com/sindresorhus/capture-website/blob/master/index.d.ts and add the option to https://github.com/sindresorhus/capture-website-cli

**Comment by nikkki** [comment]
PRs: [capture-website-cli](https://github.com/sindresorhus/capture-website-cli/pull/7) and [capture-website](https://github.com/sindresorhus/capture-website/pull/21)

**Comment by sindresorhus** [comment]
For anyone wanting to work on this, you can continue where https://github.com/sindresorhus/capture-website/pull/21 and https://github.com/sindresorhus/capture-website-cli/pull/7 left off. Just make sure you address the feedback.
