### ISSUE TITLE
Add `{javascript: false}` option

### ISSUE THREAD

**Issue by Aviortheking** [sindresorhus/capture-website#25]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/capture-website/issues/25)

Add an option to disable scripts on the webpage

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#34 `javascriptEnabled` options](https://issuehunt.io/r/sindresorhus/capture-website/pull/34)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/capture-website/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
What's the use-case? Such option would disable a lot of the other options which rely on executing JS on the page.

**Comment by Aviortheking** [comment]
Well for example making the creation of the screenshot quicker to quickly send it to a webpage or something like that
For other cases it can remove the cookie consent bar at the bottom for sites that use js to load it

**Comment by sindresorhus** [comment]
Seems like it's possible with Puppeteer:

- https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetjavascriptenabledenabled
- https://stackoverflow.com/questions/51897899/how-to-stop-all-js-scripts-in-puppeteer
