### ISSUE TITLE
Wait for lazy loaded elements when using the `fullPage` option

### ISSUE THREAD

**Issue by SilencerWeb** [sindresorhus/capture-website#28]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/capture-website/issues/28)

Is there a way to add an option that will wait until the website will be fully loaded (including lazy loading elements which loading will be triggered because of the scroll)?

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Submitted pull Requests
- [#40 Wait for lazy loaded elements when using the ullPage option](https://issuehunt.io/r/sindresorhus/capture-website/pull/40)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/capture-website/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
If it’s lazy loaded, how will capture-website even know about it?

**Comment by SilencerWeb** [comment]
Well, I'm not familiar with Puppeteer and if the scenario I have in my head is possible or not but for me it looks like this:
1. capture-website opens website
2. Waits until all resources are loaded
3. Scrolls it to the bottom to trigger all lazy loading elements
4. Waits until they are loaded
5. Makes a screenshot of the page

It should work like that if `fullPage` is set to `true. If it's not, then steps 3 and 4 should be skipped.

By the way, I'm willing to help, especially with issue #1, but as I already said, I'm not really familiar with Puppeteer or how capture-website works. If there is something that can help me to roll into the project easier, I would be thankful for sharing.

**Comment by sindresorhus** [comment]
What you're describing is ideally how the `fullPage` option should work by default.

**Comment by Vasile-Peste** [comment]
I can handle this easily. Do you still need help? Let me know, thanks.

**Comment by netrules** [comment]
Got any examples of websites this should work with? What if the website features endless scrolling?
