### ISSUE TITLE
Add a version of this library to be included in another app

### ISSUE THREAD

**Issue by JoelEllis** [sindresorhus/capture-website#29]
The basic idea of this is to allow this to be used as a library to let an app take a screenshot of itself. For example it could be used as a part of a share sheet. An app might also want to allow users to have a full page screenshot option (which is not avalable to most users in chrome without opening devtools, unlike firefox.)

**Comment by sindresorhus** [comment]
I don't understand what you're requesting. You're referring to this as an app, but it's a library.

**Comment by JoelEllis** [comment]
fixed that.  (it is a CLI app as well)

What I’m requesting is that a version of this library could be made that an app could use to take a screenshot of itself in its current state from inside the browser, without a server or any fetching of new resources. An example use case of this would be an app prompting a user to share their progress as an image, or exporting an image version of a document.

**Comment by sindresorhus** [comment]
You are still being vague. You're talking about using it in the browser, but this module doesn't run in the browser. Regardless, what you're proposing is outside the scope of this module.
