### ISSUE TITLE
Allow direct HTML input

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/capture-website#3]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/capture-website/issues/3)

It would be useful to be able to just pass a HTML string. The problem is that we can't really overload the `url` argument to accept a HTML string as it would make the parsing too ambiguous. Well, we *could* detect `<`, but then we would fail if the user thought they could just pass in a string like `Hello` without any tags. Better to make it explicit, I think.

Puppeteer docs: https://github.com/GoogleChrome/puppeteer/blob/v1.12.0/docs/api.md#pagesetcontenthtml-options

We should also add support for this in the [CLI tool](https://github.com/sindresorhus/capture-website-cli).

There are two alternatives I can think of:

#### 1. Method

`.html()` will return an object with a `html` property and a `Symbol` we check for internally so we can handle it correctly.

```js
await captureWebsite.file(captureWebsite.html('<h1>🦄</h1>'), 'screenshot.png');
```

#### 2. Option

```js
await captureWebsite.file('<h1>🦄</h1>', 'screenshot.png', {inputType: 'html'});
```
---

I'm happy to consider other solutions too.

---

> *Note: This issue has a bounty, so it's expected that you are an experienced programmer and that you give it your best effort if you intend to tackle this. Don't forget, if applicable, to add tests, docs (double-check for typos), and update TypeScript definitions. And don't be sloppy. Review your own diff multiple times and try to find ways to improve and simplify your code. Instead of asking too many questions, present solutions. The point of an issue bounty is to reduce my workload, not give me more. Include a 🦄 in your PR description to indicate that you've read this. Thanks for helping out 🙌* - @sindresorhus

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#33 Add direct HTML input support](https://issuehunt.io/r/sindresorhus/capture-website/pull/33)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/capture-website/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by kapooostin** [comment]
I'd say any of these variants would do. Maybe the second one looks more convenient.

What do you need to make a choice?

**Comment by sindresorhus** [comment]
Let's go with option 2.
