### ISSUE TITLE
hideElements and elements options not working

### ISSUE THREAD

**Issue by IsaacLaquerre** [sindresorhus/capture-website#43]
I'm creating a webscraper for a Discord bot and I scrape the webpage displaying players' info on RealmEye (for a game called Realm of the Mad God).

What I'm trying to do, essentially, is to get a character's image with a screenshot (I would just scrape the url of the image, but there's no href attribute, it's built with classes when the webpage loads).

I used `hideElements: ["#mys-content"]` (hides ads) and `elements: ".character"` (to frame the picture around the character's image). But when I run the code, it doesn't hide the ads and it just takes a pic of the full page (as seen below)

![image](https://user-images.githubusercontent.com/60407229/75459374-47317980-594d-11ea-9482-e0a25dc22a53.png)

Here's my code:
```
const captureWebsite = require('capturewebsite');

[...]

captureWebsite.file("https://www.realmeye.com/player/Vyle", "charRaw.png", {
            elements: ".character",
            hideElements: [
                "#mys-content"
            ],
            fullPage: true
        }).then(() => {
            //Handling image
        });
```

**Comment by sindresorhus** [comment]
Can you try the `delay` option? Set it to 20 seconds or something. The element might not exist yet when the website is loaded.

**Comment by IsaacLaquerre** [comment]
I just tried, doesn't work :(

**Comment by IsaacLaquerre** [comment]
Update: Even framing is around a simple `<p class="entity-name">` doesn't render it, it simply stays at position `0, 0` and takes a screenshot

Isn't there a `clip "x, y, w, h` option available most of the time?

**Comment by krnik** [comment]
I believe that instead of iterating over maybe existing elements on the page
```ts
if (options.hideElements) {
    await Promise.all(options.hideElements.map(selector => page.$$eval(selector, hideElements)));
}
```

It could be more beneficial to actually inject a `style` element to the page like this:
```ts
if (options.hideElements) await page.addStyleTag({
    content: `${options.hideElements.join(', ')} { display: none; }`
});
```

This way there should not be any situation when the element that is supposed to be hidden is not loaded when element hiding executes.

**Comment by sindresorhus** [comment]
@krnik Good idea! 👌
