### ISSUE TITLE
Is it possible to cancel the image saving?

### ISSUE THREAD

**Issue by dm-grinko** [sindresorhus/capture-website#44]
**Is it possible to cancel the image saving?**
 
```
(async () => {
    await captureWebsite.file('https://sindresorhus.com', 'screenshot.png', {
        beforeScreenshot: async (page, browser) => {
            await checkSomething(); <----- here ?
        }
    });
})();
```

**Comment by sindresorhus** [comment]
@dm-grinko If you solved problem, it's usually nice to explain how, for future onlookers.

**Comment by dm-grinko** [comment]
@sindresorhus I've solved the problem by removing this plugin from my project. Feel free to reopen it for future onlookers
