### ISSUE TITLE
Can't seem to get scrollToElement to work

### ISSUE THREAD

**Issue by gaminfish** [sindresorhus/capture-website#47]
I'm trying to use scrollToElement but for some reason, it doesn't work, I'm I've tried using lots of different elements and ways to identify them but can't get it to work. Also, I'm sorry if this is the wrong place to put this but I couldn't get help with this issue anywhere else.

**Comment by sindresorhus** [comment]
The element must be loaded when the page is loaded. If it's loaded dynamically/lazily, you must use the `waitForElement` option.

I cannot really help more than that without code that reproduces the issue.

**Comment by gaminfish** [comment]
I don't believe that the elements are loaded lazily but I am using waitForElement here's the code:
(unfortunately quite long due to multiple cookies needed)
`    if(command === 'new') {
    (async () => {
        try{
            var filename
            await captureWebsite.file('https://dragoncity.fandom.com/wiki/Eggs', 'local-file.png', {
                //clickElement: [
                 //   '._2o0B8MF50eAK1jv60jldUQ'
                //],
                cookies: [
                    //fandom
                    {
                        name: 'Geo',
                        value: '{%22region%22:%22NTH%22%2C%22country%22:%22GB%22%2C%22continent%22:%22EU%22}',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {
                        name: 'WikiaLifetimeSource',
                        value: 'https%3A%2F%2Fwww.google.com%2F',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'WikiaSessionSource',
                        value: 'https%3A%2F%2Fwww.google.com%2F',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '__gads',
                        value: 'ID=92cae0264dcff6dc:T=1584278168:S=ALNI_MZxmI1yd4Cpa-XWZcdCBvpZt-_ZYw',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '__qca',
                        value: 'P0-1581094652-1584278166241',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_dlt',
                        value: '1',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_ga',
                        value: 'GA1.2.1711467874.1584278166',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_gat',
                        value: '1',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_gid',
                        value: 'GA1.2.72121424.1591295656',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_parsely_visitor',
                        value: '{%22id%22:%22pid=841a1ac460e53475bb1d796111ff1f11%22%2C%22session_count%22:1%2C%22last_session_ts%22:1591295810875',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'access_token',
                        value: 'MDE5YzYzMGYtNzU5MC00NWM2LTg1NTYtMjUzMmU0N2UwMTYy',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'euconsent',
                        value: 'BOwTanbOwTanbCNACAENDB-AAAAugANARIiAAogiUPRAFkAACCgACAACQAQAAAAAAACAAAAASAAgAAIAAQAAEAQAAABABAAAAAAAAAAAAACAAAAAAgACAAAAAAAAAgAABAAAAAAAAAAAAAAAAAAAAAAAAA',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyDomainTestCookie',
                        value: 'null',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyEndUserId',
                        value: 'oeu1584900409916r0.29156250753475543',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyPPID',
                        value: 'null',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'permutive-id',
                        value: 'ef6e65e7-234f-4aeb-876a-7554d2df3ed7',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'permutive-session',
                        value: '%7B%22session_id%22%3A%2232ac2a5b-0046-4cc5-8ee8-35976ff207fb%22%2C%22last_updated%22%3A%222020-06-05T10%3A28%3A53.140Z%22%7D',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'pv_number_global',
                        value: '5',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking-opt-in-status',
                        value: 'accepted',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking-opt-in-version',
                        value: '2',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking_session_id',
                        value: 'b7b11475-a787-45eb-a60e-363e89cbd804',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikia_beacon_id',
                        value: 'KiUwQS0b5D',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikia_session_id',
                        value: 'cnbWvuBWE_',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikicities_session',
                        value: '8448c303aee82c701dfb312eafa1823c',
                        domain: '.fandom.com',
                        path: '/'
					},
                    //dragon city
                    {
                        name: 'ki_r',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'ki_t',
                        value: '1591360679099%3B1591360679099%3B1591360679099%3B1%3B1',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'ki_u',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'mnet_session_depth',
                        value: '1%7C1591360678076',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'mw_hidetoc',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'optimizelyDomainTestCookie',
                        value: 'null',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'optimizelyPPID',
                        value: 'null',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'pv_number',
                        value: '1',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					}                    
				],
                timeout: 0,
                waitForElement: '.dc-eggs.wikitable',
                scrollToElement:'.dc-eggs.wikitable',    
                height: 267,
                width: 716
			});
            const image = {files: ["./local-file.png"]};
            message.channel.send('Here is the wiki page:', {files: ["./local-file.png"]});
		}catch(e){
            message.channel.send('oops, an error occured, try again later when the error may be fixed. Error: ' + e)
		}finally{
            await captureWebsite.file('https://dragoncity.fandom.com/wiki/' + args[0], 'local-file.png', {
                //clickElement: [
                 //   '._2o0B8MF50eAK1jv60jldUQ'
                //],
                cookies: [
                    //fandom
                    {
                        name: 'Geo',
                        value: '{%22region%22:%22NTH%22%2C%22country%22:%22GB%22%2C%22continent%22:%22EU%22}',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {
                        name: 'WikiaLifetimeSource',
                        value: 'https%3A%2F%2Fwww.google.com%2F',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'WikiaSessionSource',
                        value: 'https%3A%2F%2Fwww.google.com%2F',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '__gads',
                        value: 'ID=92cae0264dcff6dc:T=1584278168:S=ALNI_MZxmI1yd4Cpa-XWZcdCBvpZt-_ZYw',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '__qca',
                        value: 'P0-1581094652-1584278166241',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_dlt',
                        value: '1',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_ga',
                        value: 'GA1.2.1711467874.1584278166',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_gat',
                        value: '1',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_gid',
                        value: 'GA1.2.72121424.1591295656',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: '_parsely_visitor',
                        value: '{%22id%22:%22pid=841a1ac460e53475bb1d796111ff1f11%22%2C%22session_count%22:1%2C%22last_session_ts%22:1591295810875',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'access_token',
                        value: 'MDE5YzYzMGYtNzU5MC00NWM2LTg1NTYtMjUzMmU0N2UwMTYy',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'euconsent',
                        value: 'BOwTanbOwTanbCNACAENDB-AAAAugANARIiAAogiUPRAFkAACCgACAACQAQAAAAAAACAAAAASAAgAAIAAQAAEAQAAABABAAAAAAAAAAAAACAAAAAAgACAAAAAAAAAgAABAAAAAAAAAAAAAAAAAAAAAAAAA',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyDomainTestCookie',
                        value: 'null',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyEndUserId',
                        value: 'oeu1584900409916r0.29156250753475543',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'optimizelyPPID',
                        value: 'null',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'permutive-id',
                        value: 'ef6e65e7-234f-4aeb-876a-7554d2df3ed7',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'permutive-session',
                        value: '%7B%22session_id%22%3A%2232ac2a5b-0046-4cc5-8ee8-35976ff207fb%22%2C%22last_updated%22%3A%222020-06-05T10%3A28%3A53.140Z%22%7D',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'pv_number_global',
                        value: '5',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking-opt-in-status',
                        value: 'accepted',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking-opt-in-version',
                        value: '2',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'tracking_session_id',
                        value: 'b7b11475-a787-45eb-a60e-363e89cbd804',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikia_beacon_id',
                        value: 'KiUwQS0b5D',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikia_session_id',
                        value: 'cnbWvuBWE_',
                        domain: '.fandom.com',
                        path: '/'
					},
                    {                    
                        name: 'wikicities_session',
                        value: '8448c303aee82c701dfb312eafa1823c',
                        domain: '.fandom.com',
                        path: '/'
					},
                    //dragon city
                    {
                        name: 'ki_r',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'ki_t',
                        value: '1591360679099%3B1591360679099%3B1591360679099%3B1%3B1',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'ki_u',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'mnet_session_depth',
                        value: '1%7C1591360678076',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'mw_hidetoc',
                        value: '',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'optimizelyDomainTestCookie',
                        value: 'null',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'optimizelyPPID',
                        value: 'null',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					},
                    {
                        name: 'pv_number',
                        value: '1',
                        domain: 'dragoncity.fandom.com',
                        path: '/'
					}                    
				],
                timeout: 0,
                waitForElement: '.dc-eggs.wikitable',
                scrollToElement:'.dc-eggs.wikitable',    
                height: 267,
                width: 716
			});
            const image = {files: ["./local-file.png"]};
            message.channel.send('Here is the wiki page:', {files: ["./local-file.png"]});
            fileManager.removeFile('./local-file.png');		
        }
    })();`

**Comment by netrules** [comment]
Try using ```js // code here ``` syntax in order to let us test your code. **_Or_** add it to a pen/jsfiddle.

**Comment by mre** [comment]
I have the same problem.

```js
const captureWebsite = require('capture-website');

(async () => {
  await captureWebsite.file('https://github.com/sindresorhus/capture-website', 'screenshot.png', { scrollToElement: "#readme" });
})()
```

This takes a screenshot from the top of the page.
Node version `12.18.3`, capture-website `1.2.1`.
What am I doing wrong?

**Comment by krnik** [comment]
I believe this is the issue: https://github.com/sindresorhus/capture-website/blob/master/index.js#L71-L75

Before we try to scroll the `parentElement` we should also scroll the body so that the parent element is visible. Currently we try to scroll elements that are not scrollable and/or outside the viewport.

**Comment by mre** [comment]
Thanks for the research. It worked for me so I created a PR.
