### ISSUE TITLE
Ad blocking

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/capture-website#7]
Would be awesome to have some kind of ad blocking to reduce noise in screenshots.

The best solution would be to use an existing ad blocker Chrome extension, like [uBlock Origin](https://github.com/gorhill/uBlock), but it seems it's only possible to load extension when not in headless mode (`{headless: false}`), so the Chrome window would show for a few seconds.

https://gist.github.com/sindresorhus/bca2f7d0c8b31205fa3c9f328d548c70
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#working-with-chrome-extensions

We could potentially make it opt-in and let the user know the downside.

**Comment by Kikobeats** [comment]
I recently added adblock at [browserless](https://browserless.js.org/#/)

You could use [`@browserless/goto`](https://github.com/Kikobeats/browserless/tree/master/packages/goto) or use [`adblocker`](https://github.com/cliqz-oss/adblocker) directly.

It also address https://github.com/sindresorhus/capture-website/issues/11

**Comment by brandon93s** [comment]
This could be implemented with request interceptors:

```js
const blocklist = [...];

page.on('request', (request) => {
    // psuedo-code, regex or domain checks likely required
    if (blocklist.includes(request.url())) {
        request.abort();
	}

    request.continue();
  });
```

With this implementation, `blocklist` could be provided by the user -- either a list directly or a filepath.

**Comment by stvhanna** [comment]
@brandon93s How were you able to integrate this with `capture-website`? I tried the below but the `page.on('request')` is not called. @sindresorhus is this expected or possibly a bug?

```
      beforeScreenshot: async (page, browser) => {
        page.on('request', (request) => {
          console.log('request.url()', request.url());
          if (blocklist.includes(request.url())) {
            request.abort();
          }
          request.continue();
        });
      },
```
