### ISSUE TITLE
"Running as root without --no-sandbox" After enabling user namespace cloning.

### ISSUE THREAD

**Issue by jameslinimk** [sindresorhus/capture-website#73]
![image](https://user-images.githubusercontent.com/63650909/105646923-af941e00-5e70-11eb-9a23-d29a52752336.png)
![image](https://user-images.githubusercontent.com/63650909/105646928-b753c280-5e70-11eb-95e0-88a5e2c059ee.png)
My code: 
```js
captureWebsite.buffer('https://sindresorhus.com', 'screenshot.png').then(buffer => {
  const attachemnt = new Discord.MessageAttachment(buffer);
  message.channel.send(attachemnt)
});
```

**Comment by sindresorhus** [comment]
This has nothing to do with `capture-websites`. It's coming from Puppeteer. I suggest looking at the troubleshooting page linked from the error.
