### ISSUE TITLE
Allow saving as pdf

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/capture-website#80]
[Related SA question](https://stackoverflow.com/questions/6896592/is-it-possible-to-save-html-page-as-pdf-using-javascript-or-jquery)

**Comment by sindresorhus** [comment]
Can you propose what it would look like? Maybe an `outputType` option? Does Puppeteer support PDF? If so, can you link to relevant docs?

**Comment by Richienb** [comment]
[`page.pdf`](https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-pagepdfoptions)

**Comment by hlovdal** [comment]
This is a duplicate of #108 (or actually vice versa), so this issue could probably be closed.

**Comment by sindresorhus** [comment]
Duplicate of #108
