### ISSUE TITLE
Specifying chrome-aws-lambda build for deployment as Lambda function on Netlify

### ISSUE THREAD

**Issue by platform-kit** [sindresorhus/capture-website#81]
Hi, 

is there any way to use this build of chromium + puppeteer-core?

https://github.com/alixaxel/chrome-aws-lambda

The version of puppeteer that is included is over 250mb (too large to deploy in a lambda function) - but the above build comes in at a small enough footprint.

Please advise.

**Comment by sindresorhus** [comment]
You can set a path to a custom Chromium with the `launchOptions` option: https://github.com/sindresorhus/capture-website#launchoptions

**Comment by platform-kit** [comment]
Hi @sindresorhus , did some digging on this. It seems that capture-website can be deployed to Lambda by using puppeteer-core instead of puppeteer (gets rid of unnecessary bloat). Can you provide any insights as to how I might go about pointing the puppeteer references at puppeteer core, instead?

**Comment by sindresorhus** [comment]
There's no way to use `puppeteer-core` with this package. However, you could set the environment variable `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` to prevent downloading Chrome.

https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#environment-variables
