### ISSUE TITLE
Import error with ts-node

### ISSUE THREAD

**Issue by kaihaase** [sindresorhus/capture-website#87]
I import `capture-website` (i2.0.2) in a TypeScript project via:
`import captureWebsite from 'capture-website';`

When starting the application via `ts-node` (10.0.0) I get the following error message:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ... /node_modules/capture-website/index.js
require() of ES modules is not supported.
```

I tried it in the following Node.js versions on macOS (11.4):
- v16.3.0 (npm 7.15.1)
- v14.7.1 (npm 6.14.13)

I also tried to import via:
`import * as captureWebsite from 'capture-website';`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
