### ISSUE TITLE
Want to made video by capturing images

### ISSUE THREAD

**Issue by MunnyReol** [sindresorhus/capture-website#88]
Want to made video by capturing images.
How can I do that.

**Comment by sindresorhus** [comment]
If you mean capturing a time lapse over a long period of time, you can just call this package on an interval.

If you mean actual video, this package is not really suitable for this as it only captures one image per run. I would recommend instead using a custom Puppeteer script. https://www.google.com/search?client=safari&rls=en&q=puppeteer+video&ie=UTF-8&oe=UTF-8
