### ISSUE TITLE
Can't resolve node:fs

### ISSUE THREAD

**Issue by BenCoDev** [sindresorhus/capture-website#94]
Hey Sindresorhus,

I tried to import captureWebsite, but I get the following error

```
Failed to compile.

./node_modules/capture-website/index.js
Module not found: Can't resolve 'node:fs' in '/Users/benoitcotte/App/vero/node_modules/capture-website'
```

I am currently using node v16.1.0

**Comment by sindresorhus** [comment]
This is a problem with your bundler. Open an issue there instead. `node:fs` is a completely valid import.
